---
  pid: /srv/www/vertexdb_site/thin.pid
  log: /srv/www/vertexdb_site/thin.log
  timeout: 30
  port: 6020
  max_conns: 1024
  chdir: /srv/www/vertexdb_site
  rackup: /srv/www/vertexdb_site/config.ru
  max_persistent_conns: 512
  environment: production
  address: 127.0.0.1
  servers: 1
  daemonize: true